from .batch_context_auto import NODE_CLASS_MAPPINGS as BATCH_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BATCH_DISPLAY
from .final_join_gate import NODE_CLASS_MAPPINGS as FINAL_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as FINAL_DISPLAY
from .manifest_run import NODE_CLASS_MAPPINGS as MANIFEST_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MANIFEST_DISPLAY
from .single_run_loop import NODE_CLASS_MAPPINGS as LOOP_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOOP_DISPLAY

NODE_CLASS_MAPPINGS = {**BATCH_MAPPINGS, **FINAL_MAPPINGS, **LOOP_MAPPINGS, **MANIFEST_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**BATCH_DISPLAY, **FINAL_DISPLAY, **LOOP_DISPLAY, **MANIFEST_DISPLAY}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
